from PyQt5 import QtCore, QtGui, QtWidgets
from Classes import Person
from Classes import Visitings
from Classes import Offense
from Classes import Convicts
from Classes import Dungeon
from Classes import DungeonMoves
from Classes import Selectt
from Style import Stylee

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 645)
        MainWindow.setMinimumSize(QtCore.QSize(972, 645))
        MainWindow.setMaximumSize(QtCore.QSize(972, 645))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GUI = QtWidgets.QTabWidget(self.centralwidget)
        self.GUI.setGeometry(QtCore.QRect(0, 0, 971, 311))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.GUI.setFont(font)
        self.GUI.setStyleSheet(Stylee.TabStyleGUI)
        self.GUI.setTabPosition(QtWidgets.QTabWidget.North)
        self.GUI.setTabBarAutoHide(False)
        self.GUI.setObjectName("GUI")
        self.GUIPerson = QtWidgets.QWidget()
        self.GUIPerson.setStyleSheet("background-color: rgb(229, 213, 255);")
        self.GUIPerson.setObjectName("GUIPerson")
        self.btnPA1 = QtWidgets.QPushButton(self.GUIPerson,clicked = lambda:Person.addItemPerson(self))
        self.btnPA1.setGeometry(QtCore.QRect(700, 236, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnPA1.setFont(font)
        self.btnPA1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPA1.setStyleSheet(Stylee.ButtomPerson)
        self.btnPA1.setObjectName("btnPA1")
        self.comboBoxPA1 = QtWidgets.QComboBox(self.GUIPerson)
        self.comboBoxPA1.setEnabled(True)
        self.comboBoxPA1.setGeometry(QtCore.QRect(700, 154, 133, 20))
        self.comboBoxPA1.setMinimumSize(QtCore.QSize(20, 0))
        self.comboBoxPA1.setStyleSheet(Stylee.ComboBoxGUI)
        self.comboBoxPA1.setObjectName("comboBoxPA1")
        self.comboBoxPA1.addItem("")
        self.comboBoxPA1.addItem("")
        self.btnPD1 = QtWidgets.QPushButton(self.GUIPerson,clicked = lambda :Person.getVisiting(self))
        self.btnPD1.setGeometry(QtCore.QRect(250, 130, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnPD1.setFont(font)
        self.btnPD1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPD1.setStyleSheet(Stylee.ButtomPerson)
        self.btnPD1.setObjectName("btnPD1")
        self.label_15 = QtWidgets.QLabel(self.GUIPerson)
        self.label_15.setGeometry(QtCore.QRect(580, 100, 61, 20))
        self.label_15.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.datePD2 = QtWidgets.QDateEdit(self.GUIPerson)
        self.datePD2.setGeometry(QtCore.QRect(260, 100, 111, 20))
        self.datePD2.setStyleSheet(Stylee.DateStyle)
        self.datePD2.setCalendarPopup(True)
        self.datePD2.setTimeSpec(QtCore.Qt.TimeZone)
        self.datePD2.setDate(QtCore.QDate(2022, 1, 1))
        self.datePD2.setObjectName("datePD2")
        self.btnPB1 = QtWidgets.QPushButton(self.GUIPerson,clicked = lambda:Person.delItemPerson(self))
        self.btnPB1.setGeometry(QtCore.QRect(11, 80, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnPB1.setFont(font)
        self.btnPB1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPB1.setAutoFillBackground(False)
        self.btnPB1.setStyleSheet(Stylee.ButtomPerson)
        self.btnPB1.setObjectName("btnPB1")
        self.btnAll = QtWidgets.QPushButton(self.GUIPerson,clicked = lambda:Person.AllDataPerson(self))
        self.btnAll.setGeometry(QtCore.QRect(250, 250, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnAll.setFont(font)
        self.btnAll.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAll.setStyleSheet(Stylee.ButtomPerson)
        self.btnAll.setObjectName("btnAll")
        self.label_17 = QtWidgets.QLabel(self.GUIPerson)
        self.label_17.setGeometry(QtCore.QRect(570, 190, 71, 20))
        self.label_17.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.LinePA3 = QtWidgets.QLineEdit(self.GUIPerson)
        self.LinePA3.setGeometry(QtCore.QRect(700, 102, 133, 20))
        self.LinePA3.setStyleSheet(Stylee.LineStyleGUI)
        self.LinePA3.setObjectName("LinePA3")
        self.label_16 = QtWidgets.QLabel(self.GUIPerson)
        self.label_16.setGeometry(QtCore.QRect(460, 160, 191, 21))
        self.label_16.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);\n"
"background-color: rgb(154, 82, 53);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_11 = QtWidgets.QLabel(self.GUIPerson)
        self.label_11.setGeometry(QtCore.QRect(100, 50, 111, 20))
        self.label_11.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.datePC1 = QtWidgets.QDateEdit(self.GUIPerson)
        self.datePC1.setGeometry(QtCore.QRect(460, 70, 111, 20))
        self.datePC1.setStyleSheet(Stylee.DateStyle)
        self.datePC1.setCalendarPopup(True)
        self.datePC1.setTimeSpec(QtCore.Qt.TimeZone)
        self.datePC1.setDate(QtCore.QDate(2022, 1, 1))
        self.datePC1.setObjectName("datePC1")
        self.LinePA5 = QtWidgets.QLineEdit(self.GUIPerson)
        self.LinePA5.setGeometry(QtCore.QRect(700, 206, 133, 20))
        self.LinePA5.setStyleSheet(Stylee.LineStyleGUI)
        self.LinePA5.setObjectName("LinePA5")
        self.label_7 = QtWidgets.QLabel(self.GUIPerson)
        self.label_7.setGeometry(QtCore.QRect(839, 180, 120, 20))
        self.label_7.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_22 = QtWidgets.QLabel(self.GUIPerson)
        self.label_22.setGeometry(QtCore.QRect(400, 190, 41, 20))
        self.label_22.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.datePD1 = QtWidgets.QDateEdit(self.GUIPerson)
        self.datePD1.setGeometry(QtCore.QRect(260, 70, 111, 20))
        self.datePD1.setStyleSheet(Stylee.DateStyle)
        self.datePD1.setCalendarPopup(True)
        self.datePD1.setTimeSpec(QtCore.Qt.TimeZone)
        self.datePD1.setDate(QtCore.QDate(2022, 1, 1))
        self.datePD1.setObjectName("datePD1")
        self.LinePB1 = QtWidgets.QLineEdit(self.GUIPerson)
        self.LinePB1.setGeometry(QtCore.QRect(13, 50, 81, 20))
        self.LinePB1.setStyleSheet(Stylee.LineStyleGUI)
        self.LinePB1.setObjectName("LinePB1")
        self.label_5 = QtWidgets.QLabel(self.GUIPerson)
        self.label_5.setGeometry(QtCore.QRect(839, 128, 120, 20))
        self.label_5.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.LinePA2 = QtWidgets.QLineEdit(self.GUIPerson)
        self.LinePA2.setGeometry(QtCore.QRect(700, 76, 133, 20))
        self.LinePA2.setStyleSheet(Stylee.LineStyleGUI)
        self.LinePA2.setObjectName("LinePA2")
        self.label_18 = QtWidgets.QLabel(self.GUIPerson)
        self.label_18.setGeometry(QtCore.QRect(380, 70, 61, 20))
        self.label_18.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.LinePA4 = QtWidgets.QLineEdit(self.GUIPerson)
        self.LinePA4.setGeometry(QtCore.QRect(700, 128, 133, 20))
        self.LinePA4.setStyleSheet(Stylee.LineStyleGUI)
        self.LinePA4.setObjectName("LinePA4")
        self.label_8 = QtWidgets.QLabel(self.GUIPerson)
        self.label_8.setGeometry(QtCore.QRect(839, 206, 120, 20))
        self.label_8.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(self.GUIPerson)
        self.label_13.setGeometry(QtCore.QRect(460, 40, 191, 21))
        self.label_13.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);\n"
"background-color: rgb(154, 82, 53);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_6 = QtWidgets.QLabel(self.GUIPerson)
        self.label_6.setGeometry(QtCore.QRect(848, 154, 111, 20))
        self.label_6.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.btnPF1 = QtWidgets.QPushButton(self.GUIPerson,clicked = lambda: Person.getDungeonName(self))
        self.btnPF1.setGeometry(QtCore.QRect(250, 220, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnPF1.setFont(font)
        self.btnPF1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPF1.setStyleSheet(Stylee.ButtomPerson)
        self.btnPF1.setObjectName("btnPF1")
        self.label_12 = QtWidgets.QLabel(self.GUIPerson)
        self.label_12.setGeometry(QtCore.QRect(250, 0, 401, 31))
        self.label_12.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_2 = QtWidgets.QLabel(self.GUIPerson)
        self.label_2.setGeometry(QtCore.QRect(839, 50, 120, 20))
        self.label_2.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.GUIPerson)
        self.label_4.setGeometry(QtCore.QRect(839, 102, 120, 20))
        self.label_4.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.datePC2 = QtWidgets.QDateEdit(self.GUIPerson)
        self.datePC2.setGeometry(QtCore.QRect(460, 100, 111, 20))
        self.datePC2.setStyleSheet(Stylee.DateStyle)
        self.datePC2.setCalendarPopup(True)
        self.datePC2.setTimeSpec(QtCore.Qt.TimeZone)
        self.datePC2.setDate(QtCore.QDate(2022, 1, 1))
        self.datePC2.setObjectName("datePC2")
        self.btnPC1 = QtWidgets.QPushButton(self.GUIPerson,clicked = lambda:Person.getPersonCon(self))
        self.btnPC1.setGeometry(QtCore.QRect(460, 130, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnPC1.setFont(font)
        self.btnPC1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPC1.setStyleSheet(Stylee.ButtomPerson)
        self.btnPC1.setObjectName("btnPC1")
        self.label_19 = QtWidgets.QLabel(self.GUIPerson)
        self.label_19.setGeometry(QtCore.QRect(250, 40, 201, 21))
        self.label_19.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);\n"
"background-color: rgb(154, 82, 53);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_10 = QtWidgets.QLabel(self.GUIPerson)
        self.label_10.setGeometry(QtCore.QRect(61, 0, 101, 31))
        self.label_10.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.LinePA1 = QtWidgets.QLineEdit(self.GUIPerson)
        self.LinePA1.setGeometry(QtCore.QRect(700, 50, 133, 20))
        self.LinePA1.setStyleSheet(Stylee.LineStyleGUI)
        self.LinePA1.setObjectName("LinePA1")
        self.label_14 = QtWidgets.QLabel(self.GUIPerson)
        self.label_14.setGeometry(QtCore.QRect(580, 70, 61, 20))
        self.label_14.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_21 = QtWidgets.QLabel(self.GUIPerson)
        self.label_21.setGeometry(QtCore.QRect(250, 160, 201, 21))
        self.label_21.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);\n"
"background-color: rgb(154, 82, 53);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_20 = QtWidgets.QLabel(self.GUIPerson)
        self.label_20.setGeometry(QtCore.QRect(380, 100, 61, 20))
        self.label_20.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.label_3 = QtWidgets.QLabel(self.GUIPerson)
        self.label_3.setGeometry(QtCore.QRect(839, 76, 120, 20))
        self.label_3.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.GUIPerson)
        self.label_9.setGeometry(QtCore.QRect(780, -4, 101, 31))
        self.label_9.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.btnPE1 = QtWidgets.QPushButton(self.GUIPerson,clicked = lambda: Person.getPersonOffen(self))
        self.btnPE1.setGeometry(QtCore.QRect(460, 220, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnPE1.setFont(font)
        self.btnPE1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPE1.setStyleSheet(Stylee.ButtomPerson)
        self.btnPE1.setObjectName("btnPE1")
        self.datePA1 = QtWidgets.QDateEdit(self.GUIPerson)
        self.datePA1.setGeometry(QtCore.QRect(700, 180, 133, 20))
        self.datePA1.setStyleSheet(Stylee.DateStyle)
        self.datePA1.setCalendarPopup(True)
        self.datePA1.setTimeSpec(QtCore.Qt.TimeZone)
        self.datePA1.setDate(QtCore.QDate(2022, 1, 1))
        self.datePA1.setObjectName("datePA1")
        self.comboGetOffen = QtWidgets.QComboBox(self.GUIPerson)
        self.comboGetOffen.setEnabled(True)
        self.comboGetOffen.setGeometry(QtCore.QRect(460, 188, 141, 25))
        self.comboGetOffen.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboGetOffen.setFont(font)
        self.comboGetOffen.setStyleSheet(Stylee.ComboBoxGUI)
        self.comboGetOffen.setObjectName("comboGetOffen")
        self.comboPer_2 = QtWidgets.QComboBox(self.GUIPerson)
        self.comboPer_2.setEnabled(True)
        self.comboPer_2.setGeometry(QtCore.QRect(252, 188, 151, 25))
        self.comboPer_2.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboPer_2.setFont(font)
        self.comboPer_2.setStyleSheet(Stylee.ComboBoxGUI)
        self.comboPer_2.setObjectName("comboPer_2")
        self.GUI.addTab(self.GUIPerson, "")
        self.GUIConvictsOffense = QtWidgets.QWidget()
        self.GUIConvictsOffense.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.GUIConvictsOffense.setObjectName("GUIConvictsOffense")
        self.label_29 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_29.setGeometry(QtCore.QRect(869, 155, 91, 21))
        self.label_29.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_29.setObjectName("label_29")
        self.btnCA1 = QtWidgets.QPushButton(self.GUIConvictsOffense,clicked = lambda:Convicts.AddItemConvicts(self))
        self.btnCA1.setGeometry(QtCore.QRect(711, 230, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnCA1.setFont(font)
        self.btnCA1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCA1.setStyleSheet(Stylee.ButtomOffenAndCon)
        self.btnCA1.setObjectName("btnCA1")
        self.label_30 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_30.setGeometry(QtCore.QRect(859, 84, 101, 25))
        self.label_30.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_31.setGeometry(QtCore.QRect(790, 0, 101, 31))
        self.label_31.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(85, 255, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_32.setGeometry(QtCore.QRect(869, 185, 91, 20))
        self.label_32.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_32.setObjectName("label_32")
        self.LineCA1 = QtWidgets.QLineEdit(self.GUIConvictsOffense)
        self.LineCA1.setGeometry(QtCore.QRect(710, 54, 141, 20))
        self.LineCA1.setStyleSheet(Stylee.LineStyleGUI)
        self.LineCA1.setObjectName("LineCA1")
        self.label_33 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_33.setGeometry(QtCore.QRect(869, 54, 91, 20))
        self.label_33.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_34.setGeometry(QtCore.QRect(859, 121, 101, 25))
        self.label_34.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_34.setObjectName("label_34")
        self.dateCA1 = QtWidgets.QDateEdit(self.GUIConvictsOffense)
        self.dateCA1.setGeometry(QtCore.QRect(710, 155, 141, 21))
        self.dateCA1.setStyleSheet(Stylee.DateStyle)
        self.dateCA1.setCalendarPopup(True)
        self.dateCA1.setTimeSpec(QtCore.Qt.TimeZone)
        self.dateCA1.setDate(QtCore.QDate(2022, 1, 1))
        self.dateCA1.setObjectName("dateCA1")
        self.dateCA2 = QtWidgets.QDateEdit(self.GUIConvictsOffense)
        self.dateCA2.setGeometry(QtCore.QRect(710, 185, 141, 21))
        self.dateCA2.setStyleSheet(Stylee.DateStyle)
        self.dateCA2.setCalendarPopup(True)
        self.dateCA2.setTimeSpec(QtCore.Qt.TimeZone)
        self.dateCA2.setDate(QtCore.QDate(2022, 1, 1))
        self.dateCA2.setObjectName("dateCA2")
        self.LineOA1 = QtWidgets.QLineEdit(self.GUIConvictsOffense)
        self.LineOA1.setGeometry(QtCore.QRect(480, 54, 81, 20))
        self.LineOA1.setStyleSheet(Stylee.LineStyleGUI)
        self.LineOA1.setObjectName("LineOA1")
        self.label_35 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_35.setGeometry(QtCore.QRect(578, 84, 81, 20))
        self.label_35.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_35.setObjectName("label_35")
        self.LineOA2 = QtWidgets.QLineEdit(self.GUIConvictsOffense)
        self.LineOA2.setGeometry(QtCore.QRect(480, 84, 81, 20))
        self.LineOA2.setStyleSheet(Stylee.LineStyleGUI)
        self.LineOA2.setObjectName("LineOA2")
        self.label_36 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_36.setGeometry(QtCore.QRect(568, 54, 91, 20))
        self.label_36.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_37.setGeometry(QtCore.QRect(510, 0, 101, 31))
        self.label_37.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(85, 85, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_38.setGeometry(QtCore.QRect(270, 0, 101, 31))
        self.label_38.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(85, 255, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_39.setGeometry(QtCore.QRect(339, 84, 81, 20))
        self.label_39.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_39.setObjectName("label_39")
        self.LineCD1 = QtWidgets.QLineEdit(self.GUIConvictsOffense)
        self.LineCD1.setGeometry(QtCore.QRect(250, 84, 81, 20))
        self.LineCD1.setStyleSheet(Stylee.LineStyleGUI)
        self.LineCD1.setObjectName("LineCD1")
        self.label_40 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_40.setGeometry(QtCore.QRect(109, 84, 81, 20))
        self.label_40.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_40.setObjectName("label_40")
        self.LineOD1 = QtWidgets.QLineEdit(self.GUIConvictsOffense)
        self.LineOD1.setGeometry(QtCore.QRect(20, 84, 81, 20))
        self.LineOD1.setStyleSheet(Stylee.LineStyleGUI)
        self.LineOD1.setObjectName("LineOD1")
        self.label_41 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_41.setGeometry(QtCore.QRect(40, 0, 101, 31))
        self.label_41.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(85, 85, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.GUIConvictsOffense)
        self.label_42.setGeometry(QtCore.QRect(0, 150, 671, 31))
        self.label_42.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(85, 255, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.btnOA1 = QtWidgets.QPushButton(self.GUIConvictsOffense,clicked = lambda:Offense.AddItemOffence(self))
        self.btnOA1.setGeometry(QtCore.QRect(480, 120, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnOA1.setFont(font)
        self.btnOA1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOA1.setStyleSheet(Stylee.ButtomOffenAndCon)
        self.btnOA1.setObjectName("btnOA1")
        self.btnOD1 = QtWidgets.QPushButton(self.GUIConvictsOffense,clicked =lambda: Offense.DelItemOffence(self))
        self.btnOD1.setGeometry(QtCore.QRect(20, 120, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnOD1.setFont(font)
        self.btnOD1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOD1.setStyleSheet(Stylee.ButtomOffenAndCon)
        self.btnOD1.setObjectName("btnOD1")
        self.btnCD1 = QtWidgets.QPushButton(self.GUIConvictsOffense,clicked = lambda:Convicts.DelItemCovicts(self))
        self.btnCD1.setGeometry(QtCore.QRect(250, 120, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnCD1.setFont(font)
        self.btnCD1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCD1.setStyleSheet(Stylee.ButtomOffenAndCon)
        self.btnCD1.setObjectName("btnCD1")
        self.ViewOffe = QtWidgets.QPushButton(self.GUIConvictsOffense,clicked = lambda:Offense.AllDataOffence(self))
        self.ViewOffe.setGeometry(QtCore.QRect(180, 200, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ViewOffe.setFont(font)
        self.ViewOffe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ViewOffe.setStyleSheet(Stylee.ButtomOffenAndCon)
        self.ViewOffe.setObjectName("ViewOffe")
        self.ViewConv = QtWidgets.QPushButton(self.GUIConvictsOffense,clicked = lambda:Convicts.AllDataConvicts(self))
        self.ViewConv.setGeometry(QtCore.QRect(180, 240, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ViewConv.setFont(font)
        self.ViewConv.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ViewConv.setStyleSheet(Stylee.ButtomOffenAndCon)
        self.ViewConv.setObjectName("ViewConv")
        self.comboPer = QtWidgets.QComboBox(self.GUIConvictsOffense)
        self.comboPer.setEnabled(True)
        self.comboPer.setGeometry(QtCore.QRect(710, 84, 143, 25))
        self.comboPer.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboPer.setFont(font)
        self.comboPer.setStyleSheet(Stylee.ComboBoxGUI)
        self.comboPer.setObjectName("comboPer")
        self.comboOffen = QtWidgets.QComboBox(self.GUIConvictsOffense)
        self.comboOffen.setEnabled(True)
        self.comboOffen.setGeometry(QtCore.QRect(710, 120, 143, 25))
        self.comboOffen.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboOffen.setFont(font)
        self.comboOffen.setStyleSheet(Stylee.ComboBoxGUI)
        self.comboOffen.setObjectName("comboOffen")
        self.GUI.addTab(self.GUIConvictsOffense, "")
        self.GUIVisitings = QtWidgets.QWidget()
        self.GUIVisitings.setStyleSheet("background-color: rgb(255, 199, 181);")
        self.GUIVisitings.setObjectName("GUIVisitings")
        self.LineVA1 = QtWidgets.QLineEdit(self.GUIVisitings)
        self.LineVA1.setGeometry(QtCore.QRect(630, 60, 141, 20))
        self.LineVA1.setStyleSheet(Stylee.LineStyleGUI)
        self.LineVA1.setObjectName("LineVA1")
        self.dateVA1 = QtWidgets.QDateEdit(self.GUIVisitings)
        self.dateVA1.setGeometry(QtCore.QRect(630, 160, 141, 21))
        self.dateVA1.setStyleSheet(Stylee.DateStyle)
        self.dateVA1.setCalendarPopup(True)
        self.dateVA1.setTimeSpec(QtCore.Qt.TimeZone)
        self.dateVA1.setDate(QtCore.QDate(2022, 1, 1))
        self.dateVA1.setObjectName("dateVA1")
        self.btnVA1 = QtWidgets.QPushButton(self.GUIVisitings,clicked = lambda : Visitings.AddItemVisiting(self))
        self.btnVA1.setGeometry(QtCore.QRect(630, 230, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnVA1.setFont(font)
        self.btnVA1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVA1.setStyleSheet(Stylee.ButtomVisiting)
        self.btnVA1.setObjectName("btnVA1")
        self.label_43 = QtWidgets.QLabel(self.GUIVisitings)
        self.label_43.setGeometry(QtCore.QRect(788, 160, 91, 21))
        self.label_43.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.GUIVisitings)
        self.label_44.setGeometry(QtCore.QRect(709, -4, 101, 31))
        self.label_44.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 0, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.GUIVisitings)
        self.label_45.setGeometry(QtCore.QRect(788, 60, 91, 20))
        self.label_45.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.GUIVisitings)
        self.label_46.setGeometry(QtCore.QRect(789, 92, 91, 25))
        self.label_46.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.GUIVisitings)
        self.label_47.setGeometry(QtCore.QRect(789, 130, 91, 20))
        self.label_47.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_47.setObjectName("label_47")
        self.LineVA3 = QtWidgets.QLineEdit(self.GUIVisitings)
        self.LineVA3.setGeometry(QtCore.QRect(630, 130, 141, 20))
        self.LineVA3.setStyleSheet(Stylee.LineStyleGUI)
        self.LineVA3.setObjectName("LineVA3")
        self.LineVA4 = QtWidgets.QLineEdit(self.GUIVisitings)
        self.LineVA4.setGeometry(QtCore.QRect(630, 190, 141, 20))
        self.LineVA4.setStyleSheet(Stylee.LineStyleGUI)
        self.LineVA4.setObjectName("LineVA4")
        self.label_48 = QtWidgets.QLabel(self.GUIVisitings)
        self.label_48.setGeometry(QtCore.QRect(790, 190, 91, 20))
        self.label_48.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.GUIVisitings)
        self.label_49.setGeometry(QtCore.QRect(240, 60, 91, 20))
        self.label_49.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_49.setObjectName("label_49")
        self.LineVD1 = QtWidgets.QLineEdit(self.GUIVisitings)
        self.LineVD1.setGeometry(QtCore.QRect(122, 60, 101, 20))
        self.LineVD1.setStyleSheet(Stylee.LineStyleGUI)
        self.LineVD1.setObjectName("LineVD1")
        self.label_50 = QtWidgets.QLabel(self.GUIVisitings)
        self.label_50.setGeometry(QtCore.QRect(160, 0, 101, 31))
        self.label_50.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 0, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.GUIVisitings)
        self.label_51.setGeometry(QtCore.QRect(0, 150, 461, 31))
        self.label_51.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 0, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.btnVD1 = QtWidgets.QPushButton(self.GUIVisitings,clicked = lambda:Visitings.dellItemVisiting(self))
        self.btnVD1.setGeometry(QtCore.QRect(120, 100, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnVD1.setFont(font)
        self.btnVD1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVD1.setStyleSheet(Stylee.ButtomVisiting)
        self.btnVD1.setObjectName("btnVD1")
        self.ViewVisit = QtWidgets.QPushButton(self.GUIVisitings,clicked = lambda:Visitings.AllDataVisiting(self))
        self.ViewVisit.setGeometry(QtCore.QRect(120, 220, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ViewVisit.setFont(font)
        self.ViewVisit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ViewVisit.setStyleSheet(Stylee.ButtomVisiting)
        self.ViewVisit.setObjectName("ViewVisit")
        self.comboVIstPer = QtWidgets.QComboBox(self.GUIVisitings)
        self.comboVIstPer.setEnabled(True)
        self.comboVIstPer.setGeometry(QtCore.QRect(630, 92, 143, 25))
        self.comboVIstPer.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboVIstPer.setFont(font)
        self.comboVIstPer.setStyleSheet(Stylee.ComboBoxGUI)
        self.comboVIstPer.setObjectName("comboVIstPer")
        self.GUI.addTab(self.GUIVisitings, "")
        self.GUIDungeonAndMovie = QtWidgets.QWidget()
        self.GUIDungeonAndMovie.setStyleSheet("background-color: rgb(255, 191, 169);\n"
"")
        self.GUIDungeonAndMovie.setObjectName("GUIDungeonAndMovie")
        self.label_53 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_53.setGeometry(QtCore.QRect(819, 70, 91, 20))
        self.label_53.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_53.setObjectName("label_53")
        self.ViewMovDung = QtWidgets.QPushButton(self.GUIDungeonAndMovie,clicked = lambda:DungeonMoves.AllDataDungeonMovie(self))
        self.ViewMovDung.setGeometry(QtCore.QRect(10, 230, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ViewMovDung.setFont(font)
        self.ViewMovDung.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ViewMovDung.setStyleSheet(Stylee.ButtomDungAndMoves)
        self.ViewMovDung.setObjectName("ViewMovDung")
        self.LineDA3 = QtWidgets.QLineEdit(self.GUIDungeonAndMovie)
        self.LineDA3.setGeometry(QtCore.QRect(700, 100, 101, 20))
        self.LineDA3.setStyleSheet(Stylee.LineStyleGUI)
        self.LineDA3.setObjectName("LineDA3")
        self.LineDA2 = QtWidgets.QLineEdit(self.GUIDungeonAndMovie)
        self.LineDA2.setGeometry(QtCore.QRect(700, 70, 101, 20))
        self.LineDA2.setStyleSheet(Stylee.LineStyleGUI)
        self.LineDA2.setObjectName("LineDA2")
        self.label_54 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_54.setGeometry(QtCore.QRect(819, 100, 91, 20))
        self.label_54.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_55.setGeometry(QtCore.QRect(159, 54, 91, 20))
        self.label_55.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_55.setObjectName("label_55")
        self.btnDA1 = QtWidgets.QPushButton(self.GUIDungeonAndMovie,clicked = lambda:Dungeon.addItemDungeon(self))
        self.btnDA1.setGeometry(QtCore.QRect(701, 130, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnDA1.setFont(font)
        self.btnDA1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDA1.setStyleSheet(Stylee.ButtomDungAndMoves)
        self.btnDA1.setObjectName("btnDA1")
        self.label_56 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_56.setGeometry(QtCore.QRect(828, 220, 81, 20))
        self.label_56.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_57.setGeometry(QtCore.QRect(100, 0, 101, 31))
        self.label_57.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(85, 85, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.ViewDung = QtWidgets.QPushButton(self.GUIDungeonAndMovie,clicked = lambda:Dungeon.AllDataDungeon(self))
        self.ViewDung.setGeometry(QtCore.QRect(10, 190, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ViewDung.setFont(font)
        self.ViewDung.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ViewDung.setStyleSheet(Stylee.ButtomDungAndMoves)
        self.ViewDung.setObjectName("ViewDung")
        self.label_58 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_58.setGeometry(QtCore.QRect(819, 40, 91, 20))
        self.label_58.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_59.setGeometry(QtCore.QRect(0, 130, 331, 31))
        self.label_59.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(85, 255, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.LineDA1 = QtWidgets.QLineEdit(self.GUIDungeonAndMovie)
        self.LineDA1.setGeometry(QtCore.QRect(700, 40, 101, 20))
        self.LineDA1.setStyleSheet(Stylee.LineStyleGUI)
        self.LineDA1.setObjectName("LineDA1")
        self.LineMA1 = QtWidgets.QLineEdit(self.GUIDungeonAndMovie)
        self.LineMA1.setGeometry(QtCore.QRect(380, 54, 141, 20))
        self.LineMA1.setStyleSheet(Stylee.LineStyleGUI)
        self.LineMA1.setObjectName("LineMA1")
        self.btnDD1 = QtWidgets.QPushButton(self.GUIDungeonAndMovie,clicked = lambda:Dungeon.delItemDungeon(self))
        self.btnDD1.setGeometry(QtCore.QRect(698, 250, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnDD1.setFont(font)
        self.btnDD1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDD1.setStyleSheet(Stylee.ButtomDungAndMoves)
        self.btnDD1.setObjectName("btnDD1")
        self.label_61 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_61.setGeometry(QtCore.QRect(740, 0, 101, 31))
        self.label_61.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(85, 255, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.btnMD1 = QtWidgets.QPushButton(self.GUIDungeonAndMovie,clicked = lambda:DungeonMoves.delItemDungeonMoves(self))
        self.btnMD1.setGeometry(QtCore.QRect(70, 90, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnMD1.setFont(font)
        self.btnMD1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMD1.setStyleSheet(Stylee.ButtomDungAndMoves)
        self.btnMD1.setObjectName("btnMD1")
        self.LineMD1 = QtWidgets.QLineEdit(self.GUIDungeonAndMovie)
        self.LineMD1.setGeometry(QtCore.QRect(70, 54, 81, 20))
        self.LineMD1.setStyleSheet(Stylee.LineStyleGUI)
        self.LineMD1.setObjectName("LineMD1")
        self.label_62 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_62.setGeometry(QtCore.QRect(540, 54, 91, 20))
        self.label_62.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_63.setGeometry(QtCore.QRect(748, 170, 101, 31))
        self.label_63.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(85, 255, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.btnMA1 = QtWidgets.QPushButton(self.GUIDungeonAndMovie,clicked = lambda:DungeonMoves.addItemDungeonMoves(self))
        self.btnMA1.setGeometry(QtCore.QRect(382, 186, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnMA1.setFont(font)
        self.btnMA1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMA1.setStyleSheet(Stylee.ButtomDungAndMoves)
        self.btnMA1.setObjectName("btnMA1")
        self.LineDD1 = QtWidgets.QLineEdit(self.GUIDungeonAndMovie)
        self.LineDD1.setGeometry(QtCore.QRect(698, 220, 101, 21))
        self.LineDD1.setStyleSheet(Stylee.LineStyleGUI)
        self.LineDD1.setObjectName("LineDD1")
        self.label_64 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_64.setGeometry(QtCore.QRect(450, 0, 101, 31))
        self.label_64.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(85, 85, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_65.setGeometry(QtCore.QRect(550, 85, 81, 25))
        self.label_65.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_66.setGeometry(QtCore.QRect(540, 120, 91, 25))
        self.label_66.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.GUIDungeonAndMovie)
        self.label_67.setGeometry(QtCore.QRect(540, 156, 91, 21))
        self.label_67.setStyleSheet("color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_67.setObjectName("label_67")
        self.dateMA1 = QtWidgets.QDateEdit(self.GUIDungeonAndMovie)
        self.dateMA1.setGeometry(QtCore.QRect(380, 156, 141, 21))
        self.dateMA1.setStyleSheet(Stylee.DateStyle)
        self.dateMA1.setCalendarPopup(True)
        self.dateMA1.setTimeSpec(QtCore.Qt.TimeZone)
        self.dateMA1.setDate(QtCore.QDate(2022, 1, 1))
        self.dateMA1.setObjectName("dateMA1")
        self.comboMovePer = QtWidgets.QComboBox(self.GUIDungeonAndMovie)
        self.comboMovePer.setEnabled(True)
        self.comboMovePer.setGeometry(QtCore.QRect(380, 120, 143, 25))
        self.comboMovePer.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboMovePer.setFont(font)
        self.comboMovePer.setStyleSheet(Stylee.ComboBoxGUI)
        self.comboMovePer.setObjectName("comboMovePer")
        self.comboDung = QtWidgets.QComboBox(self.GUIDungeonAndMovie)
        self.comboDung.setEnabled(True)
        self.comboDung.setGeometry(QtCore.QRect(380, 85, 143, 25))
        self.comboDung.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboDung.setFont(font)
        self.comboDung.setStyleSheet(Stylee.ComboBoxGUI)
        self.comboDung.setObjectName("comboDung")
        self.GUI.addTab(self.GUIDungeonAndMovie, "")
        self.GUISelecttt = QtWidgets.QWidget()
        self.GUISelecttt.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.GUISelecttt.setObjectName("GUISelecttt")
        self.textEdit = QtWidgets.QTextEdit(self.GUISelecttt)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 971, 161))
        self.textEdit.setStyleSheet("background-color: rgb(37, 226, 255);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.textEdit.setPlaceholderText("")
        self.textEdit.setObjectName("textEdit")
        self.btnSelView = QtWidgets.QPushButton(self.GUISelecttt,clicked = lambda:Selectt.getSelect(self))
        self.btnSelView.setGeometry(QtCore.QRect(630, 200, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnSelView.setFont(font)
        self.btnSelView.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSelView.setStyleSheet(Stylee.ButtomGUI)
        self.btnSelView.setObjectName("btnSelView")
        self.btnPA1_3 = QtWidgets.QPushButton(self.GUISelecttt,clicked = lambda:Selectt.Clearrr(self))
        self.btnPA1_3.setGeometry(QtCore.QRect(80, 200, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnPA1_3.setFont(font)
        self.btnPA1_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPA1_3.setStyleSheet(Stylee.ButtomGUI)
        self.btnPA1_3.setObjectName("btnPA1_3")
        self.GUI.addTab(self.GUISelecttt, "")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 310, 971, 251))
        self.tableWidget.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(876, 570, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Lab_Reco = QtWidgets.QLabel(self.centralwidget)
        self.Lab_Reco.setGeometry(QtCore.QRect(850, 570, 21, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Reco.setFont(font)
        self.Lab_Reco.setText("")
        self.Lab_Reco.setObjectName("Lab_Reco")
        self.btnCloss = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:MainWindow.close())
        self.btnCloss.setGeometry(QtCore.QRect(10, 570, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnCloss.setFont(font)
        self.btnCloss.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCloss.setStyleSheet(Stylee.ButtomGUI)
        self.btnCloss.setObjectName("btnCloss")
        self.btnCloss_2 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:self.reff())
        self.btnCloss_2.setGeometry(QtCore.QRect(350, 570, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnCloss_2.setFont(font)
        self.btnCloss_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCloss_2.setStyleSheet(Stylee.ButtomGUI)
        self.btnCloss_2.setObjectName("btnCloss_2")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(770, 600, 191, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("QLabel {color: rgb(85, 0, 127);}\n"
        "QLabel::hover{color: rgb(0, 170, 0);}\n")
        self.label_23.setObjectName("label_23")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.GUI.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.GUI, self.LinePA1)
        MainWindow.setTabOrder(self.LinePA1, self.LinePA2)
        MainWindow.setTabOrder(self.LinePA2, self.LinePA3)
        MainWindow.setTabOrder(self.LinePA3, self.LinePA4)
        MainWindow.setTabOrder(self.LinePA4, self.comboBoxPA1)
        MainWindow.setTabOrder(self.comboBoxPA1, self.datePA1)
        MainWindow.setTabOrder(self.datePA1, self.LinePA5)
        MainWindow.setTabOrder(self.LinePA5, self.btnPA1)
        MainWindow.setTabOrder(self.btnPA1, self.datePC1)
        MainWindow.setTabOrder(self.datePC1, self.datePC2)
        MainWindow.setTabOrder(self.datePC2, self.btnPC1)
        MainWindow.setTabOrder(self.btnPC1, self.datePD1)
        MainWindow.setTabOrder(self.datePD1, self.datePD2)
        MainWindow.setTabOrder(self.datePD2, self.btnPD1)
        MainWindow.setTabOrder(self.btnPD1, self.btnPE1)
        MainWindow.setTabOrder(self.btnPE1, self.btnPF1)
        MainWindow.setTabOrder(self.btnPF1, self.btnAll)
        MainWindow.setTabOrder(self.btnAll, self.LinePB1)
        MainWindow.setTabOrder(self.LinePB1, self.btnPB1)
        MainWindow.setTabOrder(self.btnPB1, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.LineCA1)
        MainWindow.setTabOrder(self.LineCA1, self.dateCA1)
        MainWindow.setTabOrder(self.dateCA1, self.dateCA2)
        MainWindow.setTabOrder(self.dateCA2, self.btnCA1)
        MainWindow.setTabOrder(self.btnCA1, self.LineOA1)
        MainWindow.setTabOrder(self.LineOA1, self.LineOA2)
        MainWindow.setTabOrder(self.LineOA2, self.btnOA1)
        MainWindow.setTabOrder(self.btnOA1, self.LineCD1)
        MainWindow.setTabOrder(self.LineCD1, self.btnCD1)
        MainWindow.setTabOrder(self.btnCD1, self.LineOD1)
        MainWindow.setTabOrder(self.LineOD1, self.btnOD1)
        MainWindow.setTabOrder(self.btnOD1, self.ViewOffe)
        MainWindow.setTabOrder(self.ViewOffe, self.ViewConv)
        MainWindow.setTabOrder(self.ViewConv, self.LineVA1)
        MainWindow.setTabOrder(self.LineVA1, self.LineVA3)
        MainWindow.setTabOrder(self.LineVA3, self.dateVA1)
        MainWindow.setTabOrder(self.dateVA1, self.LineVA4)
        MainWindow.setTabOrder(self.LineVA4, self.btnVA1)
        MainWindow.setTabOrder(self.btnVA1, self.LineVD1)
        MainWindow.setTabOrder(self.LineVD1, self.btnVD1)
        MainWindow.setTabOrder(self.btnVD1, self.LineDA1)
        MainWindow.setTabOrder(self.LineDA1, self.LineDA2)
        MainWindow.setTabOrder(self.LineDA2, self.LineDA3)
        MainWindow.setTabOrder(self.LineDA3, self.btnDA1)
        MainWindow.setTabOrder(self.btnDA1, self.LineDD1)
        MainWindow.setTabOrder(self.LineDD1, self.btnDD1)
        MainWindow.setTabOrder(self.btnDD1, self.LineMA1)
        MainWindow.setTabOrder(self.LineMA1, self.dateMA1)
        MainWindow.setTabOrder(self.dateMA1, self.btnMA1)
        MainWindow.setTabOrder(self.btnMA1, self.LineMD1)
        MainWindow.setTabOrder(self.LineMD1, self.btnMD1)
        MainWindow.setTabOrder(self.btnMD1, self.ViewDung)
        MainWindow.setTabOrder(self.ViewDung, self.ViewMovDung)
        MainWindow.setTabOrder(self.ViewMovDung, self.ViewVisit)

    def retranslateUi(self, MainWindow):
        ff = open("UData.txt","r")
        titel = ff.read()
        ff.close()
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", titel+" المستخدم الحالي "))
        self.btnPA1.setText(_translate("MainWindow", "إضافة"))
        self.comboBoxPA1.setItemText(0, _translate("MainWindow", "ذكر"))
        self.comboBoxPA1.setItemText(1, _translate("MainWindow", "انثى"))
        self.btnPD1.setText(_translate("MainWindow", "عرض البيانات"))
        self.label_15.setText(_translate("MainWindow", "الى التاريخ"))
        self.datePD2.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.btnPB1.setText(_translate("MainWindow", "حذف"))
        self.btnAll.setText(_translate("MainWindow", "عرض بيانات السجناء"))
        self.label_17.setText(_translate("MainWindow", "الجرم"))
        self.label_16.setText(_translate("MainWindow", "السجناء المحكومين بجرم معين"))
        self.label_11.setText(_translate("MainWindow", "الرقم التسلسلي"))
        self.datePC1.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_7.setText(_translate("MainWindow", "تاريخ الميلاد"))
        self.label_22.setText(_translate("MainWindow", "الإسم"))
        self.datePD1.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_5.setText(_translate("MainWindow", "الكنية"))
        self.label_18.setText(_translate("MainWindow", "من  التاريخ"))
        self.label_8.setText(_translate("MainWindow", "الإقامة"))
        self.label_13.setText(_translate("MainWindow", "السجناء الذين تم الحكم عليهم"))
        self.label_6.setText(_translate("MainWindow", "الجنس"))
        self.btnPF1.setText(_translate("MainWindow", "عرض البيانات"))
        self.label_12.setText(_translate("MainWindow", "عرض البيانات"))
        self.label_2.setText(_translate("MainWindow", "الرقم التسلسلي"))
        self.label_4.setText(_translate("MainWindow", "إسم الأب"))
        self.datePC2.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.btnPC1.setText(_translate("MainWindow", "عرض البيانات"))
        self.label_19.setText(_translate("MainWindow", "قائمة الزيارات التى حصلت للسجين"))
        self.label_10.setText(_translate("MainWindow", "حذف سجين"))
        self.label_14.setText(_translate("MainWindow", "من  التاريخ"))
        self.label_21.setText(_translate("MainWindow", "الزنزانات التى انتقل خلالها السجين"))
        self.label_20.setText(_translate("MainWindow", "الى التاريخ"))
        self.label_3.setText(_translate("MainWindow", "الإسم"))
        self.label_9.setText(_translate("MainWindow", "إضافة سجين"))
        self.btnPE1.setText(_translate("MainWindow", "عرض البيانات"))
        self.datePA1.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.GUI.setTabText(self.GUI.indexOf(self.GUIPerson), _translate("MainWindow", "السجناء"))
        self.label_29.setText(_translate("MainWindow", "بداية الحكم"))
        self.btnCA1.setText(_translate("MainWindow", "إضافة"))
        self.label_30.setText(_translate("MainWindow", "اسم السجين"))
        self.label_31.setText(_translate("MainWindow", "إضافة حكم"))
        self.label_32.setText(_translate("MainWindow", "نهاية الحكم"))
        self.label_33.setText(_translate("MainWindow", "معرف الحكم"))
        self.label_34.setText(_translate("MainWindow", "نوع الجرم"))
        self.dateCA1.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.dateCA2.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_35.setText(_translate("MainWindow", "نوع الجرم"))
        self.label_36.setText(_translate("MainWindow", "معرف الجرم"))
        self.label_37.setText(_translate("MainWindow", "إضافة جرم"))
        self.label_38.setText(_translate("MainWindow", "حذف حكم"))
        self.label_39.setText(_translate("MainWindow", "معرف الحكم"))
        self.label_40.setText(_translate("MainWindow", "نوع الجرم"))
        self.label_41.setText(_translate("MainWindow", "حذف جرم"))
        self.label_42.setText(_translate("MainWindow", "عرض البيانات"))
        self.btnOA1.setText(_translate("MainWindow", "إضافة"))
        self.btnOD1.setText(_translate("MainWindow", "حذف"))
        self.btnCD1.setText(_translate("MainWindow", "حذف "))
        self.ViewOffe.setText(_translate("MainWindow", "عرض بيانات الأجرام"))
        self.ViewConv.setText(_translate("MainWindow", "عرض بيانات الأحكام"))
        self.GUI.setTabText(self.GUI.indexOf(self.GUIConvictsOffense), _translate("MainWindow", "الأحكام و الأجرام"))
        self.dateVA1.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.btnVA1.setText(_translate("MainWindow", "إضافة"))
        self.label_43.setText(_translate("MainWindow", "تاريخ الزيارة"))
        self.label_44.setText(_translate("MainWindow", "إضافة زيارة"))
        self.label_45.setText(_translate("MainWindow", "معرف الزيارة"))
        self.label_46.setText(_translate("MainWindow", "إسم السجين"))
        self.label_47.setText(_translate("MainWindow", "إسم الزائر"))
        self.label_48.setText(_translate("MainWindow", "مدة الزيارة"))
        self.label_49.setText(_translate("MainWindow", "معرف الزيارة"))
        self.label_50.setText(_translate("MainWindow", "حذف زيارة"))
        self.label_51.setText(_translate("MainWindow", "عرض البيانات"))
        self.btnVD1.setText(_translate("MainWindow", "حذف"))
        self.ViewVisit.setText(_translate("MainWindow", "عرض بيانات الزيارات"))
        self.GUI.setTabText(self.GUI.indexOf(self.GUIVisitings), _translate("MainWindow", "الزيارات"))
        self.label_53.setText(_translate("MainWindow", "إسم الزنزانة"))
        self.ViewMovDung.setText(_translate("MainWindow", "عرض بيانات الإنتقالات"))
        self.label_54.setText(_translate("MainWindow", "حجم الزنزانة"))
        self.label_55.setText(_translate("MainWindow", "معرف الإنتقال"))
        self.btnDA1.setText(_translate("MainWindow", "إضافة"))
        self.label_56.setText(_translate("MainWindow", "معرف الزنزانة"))
        self.label_57.setText(_translate("MainWindow", "حذف إنتقال"))
        self.ViewDung.setText(_translate("MainWindow", "عرض بيانات الزنزانات"))
        self.label_58.setText(_translate("MainWindow", "معرف الزنزانة"))
        self.label_59.setText(_translate("MainWindow", "عرض البيانات"))
        self.btnDD1.setText(_translate("MainWindow", "حذف "))
        self.label_61.setText(_translate("MainWindow", "إضافة زنزانة"))
        self.btnMD1.setText(_translate("MainWindow", "حذف"))
        self.label_62.setText(_translate("MainWindow", "معرف الإنتقال"))
        self.label_63.setText(_translate("MainWindow", "حذف زنزانة"))
        self.btnMA1.setText(_translate("MainWindow", "إضافة"))
        self.label_64.setText(_translate("MainWindow", "إضافة إنتقال"))
        self.label_65.setText(_translate("MainWindow", "إسم الزنزانة"))
        self.label_66.setText(_translate("MainWindow", "إسم السجين"))
        self.label_67.setText(_translate("MainWindow", "تاريخ الإنتقال"))
        self.dateMA1.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.GUI.setTabText(self.GUI.indexOf(self.GUIDungeonAndMovie), _translate("MainWindow", "الزنزانات والإنتقالات"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnSelView.setText(_translate("MainWindow", "عرض البيانات"))
        self.btnPA1_3.setText(_translate("MainWindow", "مسح المحتوى"))
        self.GUI.setTabText(self.GUI.indexOf(self.GUISelecttt), _translate("MainWindow", "إستعلام"))
        self.label.setText(_translate("MainWindow", "عدد السجلات  ="))
        self.btnCloss.setText(_translate("MainWindow", "خروج"))
        self.btnCloss_2.setText(_translate("MainWindow", "تحديث البيانات"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>إعداد الطالب : علاء عبدالسلام الزيدان</p></body></html>"))
        self.reff()

    def reff(self):
        Offense.ViewOffen(self)
        Person.ViewPerson(self)
        Dungeon.ViewDungen(self)
        self.tableWidget.clear()
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setHorizontalHeaderLabels(['','','','','','','',''])
        self.Lab_Reco.setText("")
        
      